schema_version = "1.0.0"
id = "MMD_AutoFace_1"
version = "1.5.0"
name = "MMD-AutoFace"
tagline = "MMDモデルに自動で口パクと瞬きを追加するアドオンです"
maintainer = "Developer name <l35.noitamina@gmail.com>"
type = "add-on"
license = ["GPL-2.0-or-later"]
blender_version_min = "5.0.0"